### ISSUE TITLE
Add issue and PR templates

### ISSUE THREAD

**Issue by SandeepBalachandran** [BYOJS/locker#1]
Hey guys,

Noticed repository missing issue and PR templates.
So I am proposing to add issue (bug report, feature request) and PR templates to make things easier and as per conventions.

**Comment by getify** [comment]
Appreciate the contribution, but I think I'd rather keep things simpler for now. These are small projects under the BYOJS initiative, and I don't think we need all the formality for the handful of issues/PRs that may ever be filed against such a small/niche project.
